---
title: "ccRCC_single_cell_pipeline"
author: "Juechen Yang"
date: "7/27/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libs
```{r echo=FALSE}
library(Seurat)
library(tidyverse)
library(ggpubr)
library(Matrix)
plot_dir = "./plots/"
```

# load all data
```{r}
#5-----------------------------
RCC2_Kid_N_ldc_1_1.data <- Read10X(data.dir = "raw_data/4602STDY6976426")
RCC2_Kid_N_ldc_1_1 <- CreateSeuratObject(counts = RCC2_Kid_N_ldc_1_1.data, project = "RCC2_Kid_N_ldc_1_1", min.cells = 3, min.features = 200)
RCC2_Kid_N_ldc_1_1$patient="PatientF"
RCC2_Kid_N_ldc_1_1$tissue="Normal"
RCC2_Kid_N_ldc_1_1$cd45="CD45-"
RCC2_Kid_N_ldc_1_1$batch="batch0"
RCC2_Kid_N_ldc_1_1$gender="female"
#6-----------------------------
RCC2_Kid_N_ldc_1_2.data <- Read10X(data.dir = "raw_data/4602STDY6976427")
RCC2_Kid_N_ldc_1_2 <- CreateSeuratObject(counts = RCC2_Kid_N_ldc_1_2.data, project = "RCC2_Kid_N_ldc_1_2", min.cells = 3, min.features = 200)
RCC2_Kid_N_ldc_1_2$patient="PatientF"
RCC2_Kid_N_ldc_1_2$tissue="Normal"
RCC2_Kid_N_ldc_1_2$cd45="CD45-"
RCC2_Kid_N_ldc_1_2$batch="batch0"
RCC2_Kid_N_ldc_1_2$gender="female"
#7-----------------------------
RCC2_Kid_N_ldc_1_3.data <- Read10X(data.dir = "raw_data/4602STDY6976428")
RCC2_Kid_N_ldc_1_3 <- CreateSeuratObject(counts = RCC2_Kid_N_ldc_1_3.data, project = "RCC2_Kid_N_ldc_1_3", min.cells = 3, min.features = 200)
RCC2_Kid_N_ldc_1_3$patient="PatientF"
RCC2_Kid_N_ldc_1_3$tissue="Normal"
RCC2_Kid_N_ldc_1_3$cd45="CD45-"
RCC2_Kid_N_ldc_1_3$batch="batch0"
RCC2_Kid_N_ldc_1_3$gender="female"

#5-----------------------------
RCC2_Kid_T_ldc_1_1.data <- Read10X(data.dir = "raw_data/4602STDY6976422")
RCC2_Kid_T_ldc_1_1 <- CreateSeuratObject(counts = RCC2_Kid_T_ldc_1_1.data, project = "RCC2_Kid_T_ldc_1_1", min.cells = 3, min.features = 200)
RCC2_Kid_T_ldc_1_1$patient="PatientF"
RCC2_Kid_T_ldc_1_1$tissue="Tumor"
RCC2_Kid_T_ldc_1_1$cd45="CD45-"
RCC2_Kid_T_ldc_1_1$batch="batch0"
RCC2_Kid_T_ldc_1_1$gender="female"
#6-----------------------------
RCC2_Kid_T_ldc_1_2.data <- Read10X(data.dir = "raw_data/4602STDY6976423")
RCC2_Kid_T_ldc_1_2 <- CreateSeuratObject(counts = RCC2_Kid_T_ldc_1_2.data, project = "RCC2_Kid_T_ldc_1_2", min.cells = 3, min.features = 200)
RCC2_Kid_T_ldc_1_2$patient="PatientF"
RCC2_Kid_T_ldc_1_2$tissue="Tumor"
RCC2_Kid_T_ldc_1_2$cd45="CD45-"
RCC2_Kid_T_ldc_1_2$batch="batch0"
RCC2_Kid_T_ldc_1_2$gender="female"
#7-----------------------------
RCC2_Kid_T_ldc_2_1.data <- Read10X(data.dir = "raw_data/4602STDY6976424")
RCC2_Kid_T_ldc_2_1 <- CreateSeuratObject(counts = RCC2_Kid_T_ldc_2_1.data, project = "RCC2_Kid_T_ldc_2_1", min.cells = 3, min.features = 200)
RCC2_Kid_T_ldc_2_1$patient="PatientF"
RCC2_Kid_T_ldc_2_1$tissue="Tumor"
RCC2_Kid_T_ldc_2_1$cd45="CD45-"
RCC2_Kid_T_ldc_2_1$batch="batch0"
RCC2_Kid_T_ldc_2_1$gender="female"
#8-----------------------------
RCC2_Kid_T_ldc_2_2.data <- Read10X(data.dir = "raw_data/4602STDY6976425")
RCC2_Kid_T_ldc_2_2 <- CreateSeuratObject(counts = RCC2_Kid_T_ldc_2_2.data, project = "RCC2_Kid_T_ldc_2_2", min.cells = 50, min.features = 200)
RCC2_Kid_T_ldc_2_2$patient="PatientF"
RCC2_Kid_T_ldc_2_2$tissue="Tumor"
RCC2_Kid_T_ldc_2_2$cd45="CD45-"
RCC2_Kid_T_ldc_2_2$batch="batch0"
RCC2_Kid_T_ldc_2_2$gender="female"

#1-----------------------------
RCC1_Kid_T_ldc_1_1.data <- Read10X(data.dir = "raw_data/4602STDY6930850")
RCC1_Kid_T_ldc_1_1 <- CreateSeuratObject(counts = RCC1_Kid_T_ldc_1_1.data, project = "RCC1_Kid_T_ldc_1_1", min.cells = 50, min.features = 200)
RCC1_Kid_T_ldc_1_1$patient="PatientM"
RCC1_Kid_T_ldc_1_1$tissue="Tumor"
RCC1_Kid_T_ldc_1_1$cd45="CD45-"
RCC1_Kid_T_ldc_1_1$batch="batch0"
RCC1_Kid_T_ldc_1_1$gender="male"
#2-----------------------------
RCC1_Kid_T_ldc_1_2.data <- Read10X(data.dir = "raw_data/4602STDY6930851")
RCC1_Kid_T_ldc_1_2 <- CreateSeuratObject(counts = RCC1_Kid_T_ldc_1_2.data, project = "RCC1_Kid_T_ldc_1_2", min.cells = 50, min.features = 200)
RCC1_Kid_T_ldc_1_2$patient="PatientM"
RCC1_Kid_T_ldc_1_2$tissue="Tumor"
RCC1_Kid_T_ldc_1_2$cd45="CD45-"
RCC1_Kid_T_ldc_1_2$batch="batch0"
RCC1_Kid_T_ldc_1_2$gender="male"
#3-----------------------------
RCC1_Kid_T_ldc_2_1.data <- Read10X(data.dir = "raw_data/4602STDY6930854")
RCC1_Kid_T_ldc_2_1 <- CreateSeuratObject(counts = RCC1_Kid_T_ldc_2_1.data, project = "RCC1_Kid_T_ldc_2_1", min.cells = 50, min.features = 200)
RCC1_Kid_T_ldc_2_1$patient="PatientM"
RCC1_Kid_T_ldc_2_1$tissue="Tumor"
RCC1_Kid_T_ldc_2_1$cd45="CD45-"
RCC1_Kid_T_ldc_2_1$batch="batch0"
RCC1_Kid_T_ldc_2_1$gender="male"
#4-----------------------------
RCC1_Kid_T_ldc_2_2.data <- Read10X(data.dir = "raw_data/4602STDY6930855")
RCC1_Kid_T_ldc_2_2 <- CreateSeuratObject(counts = RCC1_Kid_T_ldc_2_2.data, project = "RCC1_Kid_T_ldc_2_2", min.cells = 50, min.features = 200)
RCC1_Kid_T_ldc_2_2$patient="PatientM"
RCC1_Kid_T_ldc_2_2$tissue="Tumor"
RCC1_Kid_T_ldc_2_2$cd45="CD45-"
RCC1_Kid_T_ldc_2_2$batch="batch0"
RCC1_Kid_T_ldc_2_2$gender="male"


#5-----------------------------
RCC1_Kid_N_ldc_1_1.data <- Read10X(data.dir = "raw_data/4602STDY6930852")
RCC1_Kid_N_ldc_1_1 <- CreateSeuratObject(counts = RCC1_Kid_N_ldc_1_1.data, project = "RCC1_Kid_N_ldc_1_1", min.cells = 50, min.features = 200)
RCC1_Kid_N_ldc_1_1$patient="PatientM"
RCC1_Kid_N_ldc_1_1$tissue="Normal"
RCC1_Kid_N_ldc_1_1$cd45="CD45-"
RCC1_Kid_N_ldc_1_1$batch="batch0"
RCC1_Kid_N_ldc_1_1$gender="male"
#6-----------------------------
RCC1_Kid_N_ldc_1_2.data <- Read10X(data.dir = "raw_data/4602STDY6930853")
RCC1_Kid_N_ldc_1_2 <- CreateSeuratObject(counts = RCC1_Kid_N_ldc_1_2.data, project = "RCC1_Kid_N_ldc_1_2", min.cells = 50, min.features = 200)
RCC1_Kid_N_ldc_1_2$patient="PatientM"
RCC1_Kid_N_ldc_1_2$tissue="Normal"
RCC1_Kid_N_ldc_1_2$cd45="CD45-"
RCC1_Kid_N_ldc_1_2$batch="batch0"
RCC1_Kid_N_ldc_1_2$gender="male"
#7-----------------------------
RCC1_Kid_N_ldc_2_1.data <- Read10X(data.dir = "raw_data/4602STDY6930856")
RCC1_Kid_N_ldc_2_1 <- CreateSeuratObject(counts = RCC1_Kid_N_ldc_2_1.data, project = "RCC1_Kid_N_ldc_2_1", min.cells = 50, min.features = 200)
RCC1_Kid_N_ldc_2_1$patient="PatientM"
RCC1_Kid_N_ldc_2_1$tissue="Normal"
RCC1_Kid_N_ldc_2_1$cd45="CD45-"
RCC1_Kid_N_ldc_2_1$batch="batch0"
RCC1_Kid_N_ldc_2_1$gender="male"
#8-----------------------------
RCC1_Ure_N_ldc_1_1.data <- Read10X(data.dir = "raw_data/4602STDY6930857")
RCC1_Ure_N_ldc_1_1 <- CreateSeuratObject(counts = RCC1_Ure_N_ldc_1_1.data, project = "RCC1_Ure_N_ldc_1_1", min.cells = 50, min.features = 200)
RCC1_Ure_N_ldc_1_1$patient="PatientM"
RCC1_Ure_N_ldc_1_1$tissue="Normal"
RCC1_Ure_N_ldc_1_1$cd45="CD45-"
RCC1_Ure_N_ldc_1_1$batch="batch0"
RCC1_Ure_N_ldc_1_1$gender="male"
```

# collect seurat obj into couple sets
```{r}
RCC1_N = c(RCC1_Kid_N_ldc_1_1, RCC1_Kid_N_ldc_1_2, RCC1_Kid_N_ldc_2_1, RCC1_Ure_N_ldc_1_1)
RCC1_T = c(RCC1_Kid_T_ldc_1_1, RCC1_Kid_T_ldc_1_2, RCC1_Kid_T_ldc_2_1, RCC1_Kid_T_ldc_2_2)
RCC2_N = c(RCC2_Kid_N_ldc_1_1, RCC2_Kid_N_ldc_1_2, RCC2_Kid_N_ldc_1_3)
RCC2_T = c(RCC2_Kid_T_ldc_1_1, RCC2_Kid_T_ldc_1_2, RCC2_Kid_T_ldc_2_1, RCC2_Kid_T_ldc_2_2)

ccrcc_all = list(RCC1_N, RCC1_T, RCC2_N, RCC2_T)
names(ccrcc_all) = c("RCC1_N", "RCC1_T", "RCC2_N", "RCC2_T")
```

# generate qc plots for 4 groups
```{r echo=FALSE}
for(j in seq(1, length(ccrcc_all))){
  qc_plt_list = list()
  pca_plt_list = list()
  for(i in seq(1,length(ccrcc_all[[j]]))){
    ccrcc = ccrcc_all[[j]][[i]]
    #Get mt percent data
    ccrcc <- ccrcc %>% PercentageFeatureSet(pattern = "^MT-", col.name = "percent.mt")
    #Filter data
    ccrcc = ccrcc %>% subset(subset =  nFeature_RNA < quantile(ccrcc@meta.data$nFeature_RNA,0.8)[[1]] & 
                             nCount_RNA < quantile(ccrcc@meta.data$nCount_RNA,0.8)[[1]] &
                             percent.mt < quantile(ccrcc@meta.data$percent.mt,0.8)[[1]])
    #Plot distribution of 3 qc vars
    qc_plt = VlnPlot(ccrcc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
    qc_plt_list[[i]] = qc_plt
    #Normalize data
    ccrcc = ccrcc %>% NormalizeData(scale.factor = 10000) %>% FindVariableFeatures() %>% ScaleData()
    #Run PCA
    ccrcc <- RunPCA(ccrcc, features = VariableFeatures(object = ccrcc))
    pca_plt = DimPlot(ccrcc)
    pca_plt_list[[i]] = pca_plt
    
  }
  #save qc plots
  qc_plt_combined = CombinePlots(qc_plt_list)
  ggsave(paste0(plot_dir, names(ccrcc_all)[[j]], "_qc.pdf"), qc_plt_combined, width = 15, height = 10)
  #save pca plots
  pca_plt_combined = CombinePlots(pca_plt_list)
  ggsave(paste0(plot_dir, names(ccrcc_all)[[j]], "_pca.pdf"), pca_plt_combined, width = 15, height = 10)
}
```

